apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "nginx.name" . }}
  name: deploy-test
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: 
    app: {{ include "nginx.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginx.name" . }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources: {{- toYaml .Values.resources | nindent 12 }}