apiVersion: v1
kind: Service
metadata:
  name: deploy-test
  labels:
    app: {{ include "nginx.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "nginx.name" . }}